---
- hosts: all
  vars_files:
  - ./defaults/main.yaml
  handlers:
  - include_tasks: handlers/main.yaml
  tasks:
  - name: Test role as a playbook
    import_tasks: tasks/main.yaml
    become: true
